version: '3.7'

services:
    dev-database:
        image: postgres:13
        container_name: dev_database
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
            - ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
        networks:
            - kittybot-dev
        ports:
            - 5432:5432
    dev-pgadmin:
        image: dpage/pgadmin4:4
        container_name: dev_pgadmin
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./.data/pgadmin/:/var/lib/pgadmin/
        networks:
            - kittybot-dev
        ports:
            - 90:80
            - 99:443
    dev-lavalink:
        image: fredboat/lavalink:dev
        container_name: dev_lavalink_1
        restart: unless-stopped
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - kittybot-dev
        ports:
            - 2333:2333

networks:
    kittybot-dev:
        name: kittybot-dev