version: '3.7'

services:
    dev-database:
        image: postgres:13
        container_name: dev_database
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=kittybot
        env_file:
            - conf.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - kittybot-dev
        ports:
            - 5432:5432
    dev-lavalink:
        image: fredboat/lavalink:dev-
        container_name: dev_lavalink
        restart: unless-stopped
        command: -Xmx128m 
        labels:
            - io.portainer.accesscontrol.teams=kittybot
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - kittybot-dev
        ports:
            - 2333:2333

networks:
    kittybot-dev:
        name: kittybot-dev
