version: '3.7'

services:
    dns:
        image: diniamo/dns:latest
        container_name: dns
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=dns
        volumes:
            - ./config.yml:/home/dns/config.yml
            - ./ffmpeg:/home/dns/ffmpeg
        networks:
            - dns

networks:
    dns:
        name: dns
