version: 3.7

services:
    kitsune-bot:
        image: topisenpai/kitsune-bot:latest
        container_name: kitsune-bot
        restart: unless-stopped
        env_file:
            - conf.env
        networks:
            - kitsune-bot
            - traefik
        expose:
            - 80
        labels:
            traefik.enable: true
            traefik.http.routers.kitsune-bot.rule: Host(`kitsune-bot.$PRIMARY_DOMAIN`)
            traefik.http.routers.kitsune-bot.entrypoints: https
            traefik.http.services.kitsune-bot.loadbalancer.server.port: 80

networks:
    kitsune-bot:
        name:  kitsune-bot
