version: '3.7'

services:
    bot:
        image: topisenpai/kittybot:latest
        container_name: kittybot_bot
        restart: always
        expose:
            - 6969
        volumes:
            - ./config.yml:/home/kittybot/config.yml
        env_file: 
            - conf.env
        networks:
            - kittybot
            - database
        depends_on:
            - lavalink
    lavalink:
        image: fredboat/lavalink:dev-
        container_name: kittybot_lavalink_1
        restart: always
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - kittybot

networks:
    kittybot:
        name: kittybot
    database:
        external: true