version: '3.7'

services:
    kittybot:
        image: topisenpai/kittybot:latest
        container_name: kittybot
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=kittybot
            - traefik.enable=true
            - traefik.http.routers.plex.rule=Host(`api.$PRIMARY_DOMAIN`)
            - traefik.http.routers.plex.entrypoints=https
        env_file: 
            - conf.env
        volumes:
            - ./config.json:/home/kittybot/config.json
        networks:
            - kittybot
            - database
        expose:
            - 6969
        depends_on:
            - lavalink
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:6969/health_check"]
            interval: 1m00s
            timeout: 5s
            retries: 3
            start_period: 1m00s
    website:
        image: topisenpai/kittybot-website:latest
        container_name: kittybot_website
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=kittybot
            - traefik.enable=true
            - traefik.http.routers.plex.rule=Host(`$PRIMARY_DOMAIN`)
            - traefik.http.routers.plex.entrypoints=https
        networks:
            - kittybot
        expose:
            - 80
        depends_on:
            - kittybot
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:80"]
            interval: 1m00s
            timeout: 5s
            retries: 3
            start_period: 1m00s
    lavalink:
        image: fredboat/lavalink:dev
        container_name: lavalink_1
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=kittybot
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - kittybot
        expose:
            - 2333

networks:
    kittybot:
        name: kittybot
    database:
        external: true
