version: '3.7'

services:
    bot:
        image: topisenpai/kittybot:latest
        container_name: kittybot_bot
        restart: always
        env_file: 
            - conf.env
        volumes:
            - ./config.yml:/home/kittybot/config.yml
        networks:
            - kittybot
            - database
        expose:
            - 6969
        depends_on:
            - lavalink
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:6969/health_check"]
            interval: 1m00s
            timeout: 5s
            retries: 3
            start_period: 1m00s
    lavalink:
        image: fredboat/lavalink:dev
        container_name: kittybot_lavalink_1
        restart: always
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - kittybot
        expose:
            - 2333

networks:
    kittybot:
        name: kittybot
    database:
        external: true
