version: '3.7'

services:
    bot:
        image: topisenpai/kittybot:latest
        container_name: kittybot_bot
        restart: always
        volumes:
            - ./config.yml:/home/KittyBot/config.yml
        env_file:
            - config.yml
        networks:
            - kittybot
            - database
        depends_on:
            - lavalink
    lavalink:
        image: fredboat/lavalink:master-
        container_name: kittybot_lavalink_1
        restart: always
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - kittybot

networks:
    kittybot:
        name: kittybot
    database:
        external: true