version: '3.7'

services:
    bot:
        image: topisenpai/kittybot:latest
        container_name: kittybot_bot
        restart: always
        expose:
            - 6969
        volumes:
            - ./config.yml:/home/kittybot/config.yml
        environment: 
            - SENTRY_DSN=https://d1cc5a7e9d3542d983397e7ba37e5687@o408367.ingest.sentry.io/5279069 java -jar app.jar
        networks:
            - kittybot
            - database
        depends_on:
            - lavalink
    lavalink:
        image: fredboat/lavalink:dev-
        container_name: kittybot_lavalink_1
        restart: always
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - kittybot

networks:
    kittybot:
        name: kittybot
    database:
        external: true