version: '3.7'

services:
    kittybot:
        image: topisenpai/kittybot:latest
        container_name: kittybot
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./config.json:/home/kittybot/config.json
        networks:
            - kittybot
            - database
            - lavalink
            - traefik
        expose:
            - 6969
        depends_on:
            - lavalink
        labels:
            io.portainer.accesscontrol.teams: kittybot
            traefik.enable: true
            traefik.http.routers.kittybot.rule: Host(`api.$PRIMARY_DOMAIN`)
            traefik.http.routers.kittybot.entrypoints: https
            traefik.http.services.kittybot.loadbalancer.server.port: 6969
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:6969/health_check']
            interval: 1m00s
            timeout: 5s
            retries: 3
            start_period: 1m00s
    website:
        image: topisenpai/kittybot-website:latest
        container_name: kittybot_website
        restart: unless-stopped
        networks:
            - kittybot
            - traefik
        expose:
            - 80
        depends_on:
            - kittybot
        labels:
            io.portainer.accesscontrol.teams: kittybot
            traefik.enable: true
            traefik.http.routers.website.rule: Host(`$PRIMARY_DOMAIN`) || Host(`www.$PRIMARY_DOMAIN`)
            traefik.http.routers.website.entrypoints: https
            traefik.http.services.website.loadbalancer.server.port: 80
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:80']
            interval: 1m00s
            timeout: 5s
            retries: 3
            start_period: 1m00s
    lavalink:
        image: fredboat/lavalink:dev
        container_name: lavalink_1
        restart: unless-stopped
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml
        networks:
            - lavalink
        expose:
            - 2333
        labels:
            io.portainer.accesscontrol.teams: kittybot

networks:
    kittybot:
        name: kittybot
    lavalink:
        name: lavalink
    database:
        external: true
    traefik:
        external: true
