version: '3.7'

services:
    hastebin:
        image: rlister/hastebin
        container_name: hastebin
        restart: always
        environment:
            - STORAGE_TYPE=redis
            - STORAGE_HOST=redis
        depends_on:
            - redis
        networks:
            - hastebin
            - redis
        expose:
            - 7777
    redis:
        image: redis:buster
        container_name: redis
        restart: always
        volumes:
            - ./.data:/data
        networks:
            - redis
            - hastebin
        entrypoint: redis-server --appendonly yes

networks:
    redis:
        name: redis
    hastebin:
        name: hastebin