version: '3.7'

services:
    hastebin:
        image: rlister/hastebin
        container_name: hastebin
        restart: unless-stopped
        environment:
            - STORAGE_TYPE=redis
            - STORAGE_HOST=redis
        depends_on:
            - redis
        networks:
            - hastebin
            - redis
            - traefik
        expose:
            - 7777
        labels:
            traefik.enable: true
            traefik.http.routers.hastebin.rule: Host(`hastebin.de`) || Host(`www.hastebin.de`) || Host(`hastebin.$PRIMARY_DOMAIN`) || Host(`hb.$PRIMARY_DOMAIN`)
            traefik.http.routers.hastebin.entrypoints: https
            traefik.http.routers.hastebin.middlewares: www-hastebin-redirect
            traefik.http.services.hastebin.loadbalancer.server.port: 7777
            traefik.http.middlewares.www-hastebin-redirect.redirectregex.regex: https://www.hastebin.de/(.*)
            traefik.http.middlewares.www-hastebin-redirect.redirectregex.replacement: https://hastebin.de/$${1}
    redis:
        image: redis:buster
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./.data:/data
        networks:
            - redis
            - hastebin
        entrypoint: redis-server --appendonly yes

networks:
    redis:
        name: redis
    hastebin:
        name: hastebin
    traefik:
        external: true
