version: '3.7'

services:
    hastebin:
        image: rlister/hastebin
        container_name: hastebin
        restart: unless-stopped
        environment:
            - STORAGE_TYPE=redis
            - STORAGE_HOST=redis
        depends_on:
            - redis
        networks:
            - hastebin
            - redis
            - traefik
        expose:
            - 7777
        labels:
            traefik.enable: true
            traefik.http.routers.website.rule: Host(`hastebin.$PRIMARY_DOMAIN`)
            traefik.http.routers.website.entrypoints: https
            traefik.http.services.website.loadbalancer.server.port: 7777
    redis:
        image: redis:buster
        container_name: redis
        restart: unless-stopped
        volumes:
            - ./.data:/data
        networks:
            - redis
            - hastebin
        entrypoint: redis-server --appendonly yes

networks:
    redis:
        name: redis
    hastebin:
        name: hastebin
    traefik:
        external: true
