version: '3.7'

services:
    server:
        image: jetbrains/teamcity-server:2020.2
        container_name: teamcity_server
        restart: unless-stopped
        volumes:
            - ./.data/server/data/:/data/teamcity_server/datadir/
            - ./.data/server/logs/:/opt/teamcity/logs/
        networks:
            - teamcity
            - database
        expose:
            - 8111
    agent_1:
        image: topisenpai/teamcity-agent:latest
        container_name: teamcity_agent_1
        restart: unless-stopped
        user: 0
        environment:
            - SERVER_URL=server:8111
            - DOCKER_IN_DOCKER=true
            - AGENT_NAME=agent_1
            - CI=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.data/agent_1/conf/:/data/teamcity_agent/conf/
            - ./.data/agent_1/work/:/opt/buildagent/work/
            - ./.data/agent_1/temp/:/opt/buildagent/temp/
            - ./.data/agent_1/tools/:/opt/buildagent/tools/
            - ./.data/agent_1/plugins/:/opt/buildagent/plugins/
            - ./.data/agent_1/system/:/opt/buildagent/system/
        networks:
            - teamcity
        depends_on:
            - server

networks:
    teamcity:
        name: teamcity
    database:
        external: true
