version: '3.8'

services:
    server:
        image: jetbrains/teamcity-server:latest
        container_name: teamcity_server
        restart: always
        volumes:
            - ./.teamcity/server/data/:/data/teamcity_server/datadir/
            - ./.teamcity/server/logs/:/opt/teamcity/logs/
        expose:
            - 8111
        networks:
            - teamcity
            - database
    agent_1:
        image: jetbrains/teamcity-agent:latest
        container_name: teamcity_agent_1
        restart: always
        user: root
        environment:
            - SERVER_URL=server:8111
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.teamcity/agent_1/conf/:/data/teamcity_agent/conf/
            - ./.teamcity/agent_1/work/:/opt/buildagent/work/
            - ./.teamcity/agent_1/temp/:/opt/buildagent/temp/
            - ./.teamcity/agent_1/tools/:/opt/buildagent/tools/
            - ./.teamcity/agent_1/plugins/:/opt/buildagent/plugins/
            - ./.teamcity/agent_1/system/:/opt/buildagent/system/
        networks:
            - teamcity
        depends_on:
            - server

networks:
    teamcity:
        name: teamcity
    database:
        external: true
