version: "3.7"

services:
    server:
        image: jetbrains/teamcity-server:latest
        container_name: teamcity_server
        restart: always
        volumes:
            - ./.teamcity/server/data/:/data/teamcity_server/datadir/:rw
            - ./.teamcity/server/logs/:/opt/teamcity/logs/:rw
        ports:
            - 8111:8111
        networks:
            - teamcity
            - database
    agent_1:
        image: jetbrains/teamcity-agent:latest
        container_name:  teamcity_agent_1
        restart: always
        environment:
            - SERVER_URL=server:8111
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.teamcity/agent_1/conf/:/data/teamcity_agent/conf/:rw
            - ./.teamcity/agent_1/work/:/opt/buildagent/work/:rw
            - ./.teamcity/agent_1/temp/:/opt/buildagent/temp/:rw
            - ./.teamcity/agent_1/tools/:/opt/buildagent/tools/:rw
            - ./.teamcity/agent_1/plugins/:/opt/buildagent/plugins/:rw
            - ./.teamcity/agent_1/system/:/opt/buildagent/system/:rw
        networks:
            - teamcity
        depends_on:
            - server

networks:
    teamcity:
        name: teamcity
    database:
        external: true