version: "3.7"

services:
    server:
        image: jetbrains/teamcity-server
        restart: always
        volumes:
            - ./.teamcity/server/data/:/data/teamcity_server/datadir/
            - ./.teamcity/server/logs/:/opt/teamcity/logs/
        ports:
            - 8111:8111
        networks:
            - teamcity
            - database
    agent:
        image: jetbrains/teamcity-agent
        restart: always
        environment:
            - SERVER_URL=server:8111
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.teamcity/agent_1/conf/:/data/teamcity_agent/conf/
            - ./.teamcity/agent_1/work/:/opt/buildagent/work/
            - ./.teamcity/agent_1/temp/:/opt/buildagent/temp/
            - ./.teamcity/agent_1/tools/:/opt/buildagent/tools/
            - ./.teamcity/agent_1/plugins/:/opt/buildagent/plugins/
            - ./.teamcity/agent_1/system/:/opt/buildagent/system/
        networks:
            - teamcity
        depends_on:
            - server

networks:
    teamcity:
    database:
        external: true