version: '3.7'

services:
    traefik:
        image: traefik
        container_name: traefik
        restart: unless-stopped
        env_file:
            - conf.env
        networks:
            - traefik
        ports:
            - '9090:8000'
            - '8080:8080'
            - '4430:4430'
        volumes:
            - ./traefik.yml:/etc/traefik/traefik.yml
            - ./.data/letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            traefik.enable: true
            traefik.http.routers.dashboard.rule: Host(`traefik.$PRIMARY_DOMAIN`)
            traefik.http.routers.dashboard.entrypoints: https
            traefik.http.routers.dashboard.middlewares: auth@docker
            traefik.http.middlewares.auth.basicauth.users: $TRAEFIK_AUTH
            traefik.http.routers.dashboard.service: api@internal

networks:
    traefik:
        name: traefik
