version: '3.7'

services:
    traefik:
        image: traefik:v2.3
        container_name: traefik
        restart: unless-stopped
        command: --api
        volumes:
            - ./traefik.yml:/traefik.yml
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - traefik
        ports:
            - 8080:8080
            - 81:80
            - 444:443

networks:
    traefik:
        name: traefik