global:
    checkNewVersion: true
    sendAnonymousUsage: true

log:
    level: INFO

metrics:
    prometheus:
        buckets:
            - 0.1
            - 0.3
            - 1.2
            - 5.0
        addEntryPointsLabels: true
        addServicesLabels: true

tls:
  options:
    default:
      minVersion: VersionTLS12

    mintls13:
      minVersion: VersionTLS13

entryPoints:
    http:
        address: ':80'
        http:
            redirections:
                entryPoint:
                    to: https
                    permanent: true
    https:
        address: ':443'
        http:
            tls:
                certResolver: default
                domains:
                    - main: 'kittybot.de'
                      sans:
                          - '*.kittybot.de'
                          - 'hastebin.de'
                          - '*.hastebin.de'
            middlewares:
                - global-errors@docker
                - global-compress@docker
                - global-headers@file

providers:
    docker:
        exposedByDefault: false
        network: traefik
    file:
        directory: "/configs"

api:
    dashboard: true

certificatesResolvers:
    default:
        acme:
            # testing server
            # caserver: https://acme-staging-v02.api.letsencrypt.org/directory
            email: tobi@strasserhof.com
            storage: /letsencrypt/acme.json
            dnsChallenge:
                provider: 'netcup'
                delayBeforeCheck: 900
