version: '3.7'

services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: unless-stopped
        volumes:
            - ./.data/grafana/:/var/lib/grafana/:rw
        networks:
            - grafana
            - prometheus
            - loki
            - database
            - kittybot-dev
            - traefik
        expose:
            - 3000
        labels:
            traefik.enable: true
            traefik.http.routers.grafana.rule: Host(`grafana.$PRIMARY_DOMAIN`)
            traefik.http.routers.grafana.entrypoints: https
            traefik.http.services.grafana.loadbalancer.server.port: 3000
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: unless-stopped
        command:
            - '--storage.tsdb.retention.time=1y'
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - prometheus
            - cadvisor
            - node-exporter
            - kittybot-dev
            - lavalink
            - traefik
        expose:
            - 9090
    node-exporter:
        image: prom/node-exporter
        container_name: node-exporter
        restart: unless-stopped
        command: --path.rootfs=/host
        pid: host
        volumes:
            - /:/host:ro,rslave
        networks: 
            - node-exporter
        expose: 
            - 9100
    cadvisor:
        image: gcr.io/google-containers/cadvisor
        container_name: cadvisor
        restart: unless-stopped
        command:
            - --docker_only=true
            - --disable_metrics=disk,percpu,sched,process
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
        networks:
            - cadvisor
        expose:
            - 8080
    loki:
        image: grafana/loki:latest
        container_name: loki
        restart: unless-stopped
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - ./local-config.yml:/etc/loki/local-config.yaml
        networks:
            - loki
        ports:
            - 127.0.0.1:3100:3100

networks:
    grafana:
        name: grafana
    prometheus:
        name: prometheus
    node-exporter:
        name: node-exporter
    kittybot-dev:
        name: kittybot-dev
    cadvisor:
        name: cadvisor
    loki:
        name: loki
    database:
        external: true
    kittybot-dev:
        external: true
    lavalink:
        external: true
    traefik:
        external: true
