global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: kittybot/prometheus
      static_configs:
          - targets: ['127.0.0.1:9090']
            labels:
                machine: kittybot

    - job_name: kittybot/dev-lavalink
      static_configs:
          - targets: ['dev_lavalink:2333']
            labels:
                machine: kittybot

    - job_name: kittybot/live-lavalink
      static_configs:
          - targets: ['lavalink:2333']
            labels:
                machine: kittybot

    - job_name: kittybot/node-exporter
      scrape_interval: 5s
      static_configs:
          - targets: ['node-exporter:9100', 'cadvisor:8080']
            labels:
                machine: kittybot

    - job_name: kittybot/traefik
      scrape_interval: 2s
      static_configs:
          - targets: ['traefik:8080']
            labels:
                machine: kittybot
