version: '3.7'

services:
    database:
        image: postgres:9.6.17-alpine
        container_name: database_1
        restart: always
        env_file:
            - config.env
        volumes:
            - ./.postgres/:/var/lib/postgresql/data/
        networks:
            - database

networks:
    database: