version: '3.7'

services:
    database:
        image: 5c0cc51367ea
        container_name: database
        restart: unless-stopped
        labels:
            - io.portainer.accesscontrol.teams=kittybot
        env_file:
            - conf.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - database
        ports:
            - 127.0.01:5432:5432
    pgadmin:
        image: dpage/pgadmin4:4
        container_name: pgadmin
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./.data/pgadmin:/var/lib/pgadmin
        networks:
            - pgadmin
            - database
        expose:
            - 80

networks:
    database:
        name: database
    pgadmin:
        name: pgadmin
