version: '3.7'

services:
    database:
        image: postgres:9.6.18-alpine
        container_name: database
        restart: always
        env_file:
            - config.env
        volumes:
            - ./.postgres/:/var/lib/postgresql/data/
        networks:
            - database
        expose:
            - 5432

networks:
    database:
        name: database
