version: '3.7'

services:
    database:
        image: postgres:9.6.17-alpine
        command: postgres -c shared_buffers=512MB c- max_wal_size = 1500MB
        container_name: database
        restart: always
        env_file:
            - config.env
        volumes:
            - ./.postgres/:/var/lib/postgresql/data/
        expose:
            - 5432
        networks:
            - database

networks:
    database:
        name: database
