version: '3.7'

services:
    database:
        image: postgres:9.6.18-alpine
        container_name: database
        restart: always
        env_file:
            - config.env
        volumes:
            - ./.data/postgres/:/var/lib/postgresql/data/
        networks:
            - database
        expose:
            - 5432
    pgadmin:
        image: dpage/pgadmin4:4
        container_name: pgadmin
        restart: always
        env_file:
            - config.env
        volumes:
            - ./.data/pgadmin:/var/lib/pgadmin
        networks:
            - pgadmin
            - database
        expose:
            - 80

networks:
    database:
        name: database
    pgadmin:
        name: pgadmin