version: '3.7'

services:
    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - watchtower
        command: --interval 30

networks:
    watchtower:
        name: watchtower