version: '3.7'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /var/www/html/:/usr/share/nginx/html/:ro
            - ./.data/certbot/conf:/etc/letsencrypt:ro
            - ./.data/certbot/www:/var/www/certbot
        networks:
            - nginx
            - teamcity
            - minecraft
            - kittybot-website
            - kittybot
            - itemwarehouse
            - portainer
        ports:
            - 80:80
            - 443:443
    certbot:
        image: certbot/certbot
        volumes:
            - ./.data/certbot/conf:/etc/letsencrypt
            - ./.data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
    nginx:
        name: nginx
    teamcity:
        external: true
    minecraft:
        external: true
    kittybot-website:
        external: true
    kittybot:
        external: true
    itemwarehouse:
        external: true
    portainer:
        external: true