version: '3.7'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /var/www/html/:/usr/share/nginx/html/:ro
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
        networks:
            - nginx
            - teamcity
        ports:
            - 80:80
            - 443:443

networks:
    nginx:
        name: nginx
    teamcity:
        external: true