version: '3.7'

services:
    nginx:
        image: staticfloat/nginx-certbot
        container_name: nginx
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./conf.d:/etc/nginx/user.conf.d:ro
            - ./.data/:/etc/letsencrypt/
        networks:
            - nginx
            - teamcity
            - minecraft
            - kittybot
            - item-warehouse
            - portainer
            - pgadmin
            - hastebin
            - grafana
        ports:
            - 80:80
            - 443:443

networks:
    nginx:
        name: nginx
    teamcity:
        external: true
    minecraft:
        external: true
    kittybot:
        external: true
    item-warehouse:
        external: true
    portainer:
        external: true
    pgadmin:
        external: true
    hastebin:
        external: true
    grafana:
        external: true
