version: '3.7'

services:
    nginx:
        image: staticfloat/nginx-certbot
        container_name: nginx
        restart: unless-stopped
        env_file:
            - conf.env
        volumes:
            - ./conf.d:/etc/nginx/user.conf.d:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./.data/:/etc/letsencrypt/
        networks:
            - nginx
            - teamcity
            - minecraft
            - kittybot
            - item-warehouse
            - portainer
            - pgadmin
            - hastebin
        ports:
            - 51820:51820/udp # vpn
            - 80:80
            - 443:500

    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        restart: unless-stopped
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Berlin
            - SERVERPORT=51820
            - PEERS=1
            - INTERNAL_SUBNET=10.13.13.0
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        network_mode: service:nginx
        volumes:
            - ./wireguard.conf:/config/wg0.conf:ro
            - /lib/modules:/lib/modules

networks:
    nginx:
        name: nginx
    teamcity:
        external: true
    minecraft:
        external: true
    kittybot:
        external: true
    item-warehouse:
        external: true
    portainer:
        external: true
    pgadmin:
        external: true
    hastebin:
        external: true
