version: '3.7'

services:
    nginx:
        image: nginx:stable-alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /var/www/html/:/usr/share/nginx/html/:ro
            - /etc/letsencrypt/:/etc/letsencrypt/:ro
        networks:
            - teamcity_default
        ports:
            - 80:80
            - 443:443

networks:
    teamcity_default:
        external: true