version: '3.7'

services:
    scope:
      image: weaveworks/scope:latest
      container_name: weavescope
      network_mode: host
      pid: "host"
      privileged: true
      labels:
          - works.weave.role=system
      env_file:
          - conf.env
      environment:
          - ENABLE_BASIC_AUTH=true
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock:rw
      command:
          - --probe.docker=true
      networks:
          - weavescope
      expose:
          - 4040
       
networks:
    weavescope:
        name: weavescope
