http:
    middlewares:
        global-sts:
            headers:
                customResponseHeaders:
                    stsincludesubdomains: false
                    stspreload: true
                    stsseconds: 31536000
                    isdevelopment: false
