version: '3.8'

services:
    portainer:
        image: portainer/portainer
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.data:/data
        networks:
            - portainer
        expose:
            - 9000
#        ports:
#            - 8000:8000 I do not need edge agent

networks:
    portainer:
        name: portainer
