version: '3.7'

services:
    portainer:
        image: portainer/portainer-ce:alpine
        container_name: portainer
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.data:/data
        networks:
            - portainer
        expose:
            - 9000

networks:
    portainer:
        name: portainer
