version: '3.7'

services:
    server:
        image: itzg/minecraft-server
        container_name: minecraft_server
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./.data:/data
        environment:
            - EULA=TRUE
            - VERSION=LATEST
            - MEMORY=2G
        ports:
            - 25565:25565
