version: '3.7'

services:
    minecraft:
        image: itzg/minecraft-server:latest
        container_name: minecraft_server
        restart: unless-stopped
        environment:
            - EULA=TRUE
            - TYPE=PAPER
            - VERSION=1.16.1
            - MEMORY=3G
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./.data:/data
        networks:
            - minecraft
        expose:
            - 25575
        ports:
            - 25565:25565

networks:
    minecraft:
        name: minecraft
