version: '3.7'

services:
    minecraft:
        image: itzg/minecraft-server
        container_name: minecraft_server
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./.data:/data
        environment:
            - EULA=TRUE
            - TYPE=PAPER
            - MEMORY=3G
        netwokrs:
            - minecraft
        ports:
            - 25565:25565
            - 25575:25575

networks:
    minecraft:
        name: minecraft