version: '3.7'

services:
    minecraft:
        image: itzg/minecraft-server:latest
        container_name: minecraft_server
        restart: unless-stopped
        environment:
            - EULA=TRUE
            - TYPE=FORGE
            - VERSION=1.12.2
            - MEMORY=4G
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - ./.data:/data
        networks:
            - minecraft
        ports:
            - 25565:25565

networks:
    minecraft:
        name: minecraft
