version: '3.8'

services:
    backend:
        image: topisenpai/item-warehouse-backend:latest
        container_name: item_warehouse_backend
        restart: always
        env_file: 
            - conf.env
        volumes:
            - ./config.yml:/home/itemwarehouse/config.yml
        networks:
            - item-warehouse
            - database
        expose:
            - 9696
    frontend:
        image: topisenpai/item-warehouse-frontend:latest
        container_name: item_warehouse_frontend
        restart: always
        networks:
            - item-warehouse
        expose:
            - 80
        depends_on:
            - backend

networks:
    item-warehouse:
        name: item-warehouse
    database:
        external: true
